version: '3.3'
services:
    server:
        container_name: onedev
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './data:/opt/onedev'
        ports:
            - '172.17.0.1:6610:6610'
            - '172.17.0.1:6611:6611'
        image: 1dev/server